create table
  public.brands (
    brand_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    brand_name text not null,
    email text not null,
    password text not null,
    constraint brands_pkey primary key (brand_id),
    constraint brands_brand_name_key unique (brand_name)
  ) tablespace pg_default;

create table
  public.reviews (
    rating_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    shoe_id bigint not null,
    user_id bigint not null,
    rating integer not null,
    comment text null,
    constraint reviews_pkey primary key (shoe_id, user_id),
    constraint reviews_shoe_id_fkey foreign key (shoe_id) references shoes (shoe_id) on update cascade on delete cascade,
    constraint reviews_user_id_fkey foreign key (user_id) references users (user_id) on update cascade on delete cascade,
    constraint ratings_comment_check check (
      (
        length(
          comment
        ) < 500
      )
    ),
    constraint ratings_rating_check check (
      (
        (rating >= 1)
        and (rating <= 5)
      )
    )
  ) tablespace pg_default;

create table
  public.shoes (
    shoe_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    brand text not null,
    price double precision not null,
    color text not null,
    material text null,
    tags text[] null,
    type text null,
    constraint shoes_pkey primary key (shoe_id)
  ) tablespace pg_default;

create table
  public.shoes_to_users (
    created_at timestamp with time zone not null default now(),
    shoe_id bigint not null,
    user_id bigint not null,
    constraint shoes_to_users_shoe_id_fkey foreign key (shoe_id) references shoes (shoe_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.users (
    user_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    username text not null,
    email text not null,
    password bytea null,
    salt bytea null,
    is_logged_in boolean null,
    constraint Users_pkey primary key (user_id),
    constraint users_email_key unique (email),
    constraint users_user_id_key unique (user_id),
    constraint users_username_key unique (username)
  ) tablespace pg_default;

INSERT INTO users (name, username, email, password)
VALUES ("Bobby Brewster", "BobsBrews", "bobby@gmail.com", "bobbybob");
INSERT INTO users (name, username, email, password)
VALUES ("Bobby Daniel", "dantheman", "danny@gmail.com", "iluvshoez");
INSERT INTO ratings (rating, comment)
VALUES (5, "Best Shoes I've Ever Owned");
/*
Initially populated the shoes table with a .csv file.
This file is in the starter_files folder: shoes.csv
*/
