create table
  public.brands (
    brand_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    brand_name text not null,
    email text not null,
    password text not null,
    constraint brands_pkey primary key (brand_id)
  ) tablespace pg_default;

create table
  public.ratings (
    rating_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    shoe_id bigint not null,
    user_id bigint not null,
    rating integer not null,
    comment text null,
    constraint ratings_pkey primary key (shoe_id, user_id),
    constraint ratings_shoe_id_fkey foreign key (shoe_id) references shoes (shoe_id) on update cascade on delete cascade,
    constraint ratings_user_id_fkey foreign key (user_id) references users (user_id) on update cascade on delete cascade,
    constraint ratings_comment_check check (
      (
        length(
          comment
        ) < 500
      )
    ),
    constraint ratings_rating_check check (
      (
        (rating >= 1)
        and (rating <= 5)
      )
    )
  ) tablespace pg_default;

create table
  public.shoes (
    shoe_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    brand text not null,
    price double precision not null,
    color text not null,
    material text null,
    tags text[] null,
    type text null,
    constraint shoes_pkey primary key (shoe_id)
  ) tablespace pg_default;

create table
  public.shoes_to_users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    shoe_id bigint null,
    user_id bigint null,
    constraint shoes_to_users_pkey primary key (id),
    constraint shoes_to_users_user_id_fkey foreign key (user_id) references users (user_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.users (
    user_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    username text not null,
    email text not null,
    password text not null,
    constraint Users_pkey primary key (user_id)
  ) tablespace pg_default;

INSERT INTO users (name, username)
VALUES (Bobby Brewster, BobsBrews);
INSERT INTO users (name, username)
VALUES (Bobby Daniel, dantheman);
INSERT INTO ratings (rating, comment)
VALUES (5, "Best Shoes I've Ever Owned");
